### ISSUE TITLE
problem with python

### ISSUE THREAD

**Issue by elwla** [Floobits/floobits-vim#14]
Hello! 
When I try :BundleInstall with: Bundle 'Floobits' I receive this message: "Sorry, the Floobits Vim plugin requires a Vim compiled with +python".

I have a repository's vim version... the only way is compiling a versión with python? or I can install my own version from respository?

thanks.

**Comment by Choongkyu** [comment]
I'm actually getting the same issue when running neovim 0.1.7 on ubuntu xenial.  will I need to switch from neovim to vim-lesstif?

**Comment by outkine** [comment]
I'm also getting this message in the latest neovim.

```
## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /home/anton/.asdf/shims/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.7.3
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.
```
