### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by nilbus** [Floobits/floobits-vim#5]
Connecting to my room in vim with `FlooJoinRoom https://floobits.com/r/nilbus/my_room` fails with:

```
Error connecting:[Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

Connecting with http instead of https works, even though I selected Require SSL (which is perhaps a separate issue)

**Comment by zebralight** [comment]
I am currently having this issue, don't mean to necropost but it's currently an issue for me on sublime text 3 and vim/neovim.
