### ISSUE TITLE
Error on open vim 8.0.66,

### ISSUE THREAD

**Issue by mrvon** [Floobits/floobits-vim#83]
Hi, That's a error occurs when I open my vim.
--------------------------------------------------------------

Error detected while processing function <SNR>81_SetAutoCmd:
line   22:
E117: Unknown function: setinterval

**Comment by knubie** [comment]
@mrvon were you able to resolve this error? Getting the same error when I launch as well.

**Comment by mrvon** [comment]
@knubie nope, ：）

**Comment by robertmaxwilliams** [comment]
I think I have the same issue. Using macvim:
```
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 17 2018 23:04:26)
macOS version
```
and Vundle.

Here's the error:
```
Error detected while processing function <SNR>18_SetAutoCmd:
line   22:
E117: Unknown function: setinterval
```
And I can't get my file to sync or anything to happen really.

**Comment by alevy** [comment]
I'm having the same issue with vim on linux. Same error as @robertmaxwilliams and can't do anything really with a project (":FlooJoinWorkspace [myworkspace]" says it's connecting, but nothing happens)
